-- MySQL Script generated by MySQL Workbench
-- Sat May 11 11:22:54 2024
-- Model: New Model    Version: 1.1
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS flashcards_db DEFAULT CHARACTER SET utf8;
USE flashcards_db;

-- -----------------------------------------------------
-- Table decks
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS decks (
  uuid BINARY(16) NOT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(200) NULL,
  PRIMARY KEY (uuid)
);

-- -----------------------------------------------------
-- Table cards
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cards (
  uuid BINARY(16) NOT NULL,
  question VARCHAR(100) NOT NULL,
  answer VARCHAR(100) NOT NULL,
  repetitions INT UNSIGNED NOT NULL DEFAULT 0,
  easiness DOUBLE NOT NULL DEFAULT 2.5,
  interval_days INT UNSIGNED NOT NULL DEFAULT 0,
  date_to_repeat TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (uuid)
);

-- -----------------------------------------------------
-- Table decks_cards
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS decks_cards (
  deck_uuid BINARY(16) NOT NULL,
  card_uuid BINARY(16) NOT NULL,
  FOREIGN KEY (deck_uuid) REFERENCES decks(uuid),
  FOREIGN KEY (card_uuid) REFERENCES cards(uuid),
  PRIMARY KEY (deck_uuid, card_uuid)
);
